CREATE DATABASE IF NOT EXISTS person_db;
USE person_db;

CREATE TABLE IF NOT EXISTS person (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dni VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  surname VARCHAR(100) NOT NULL,
  address VARCHAR(200) NOT NULL,
  birth_date DATE NOT NULL
);